Chinese Translation - Issue 6
AlternativeFFFF/Alt-F4 pull request #174
Opened 2020-09-25 23:07 UTC by pigheadx

Chinese Translation - Issue 6

2020-09-25 23:12 UTC, Conor12345 approved these changes

2020-09-25 23:17 UTC, justchen1369 approved these changes

2020-09-26 08:51 UTC, Firerazer requested changes
Title and transcription of the issue are not translated

2020-09-26 12:50 UTC, Firerazer approved these changes
approved :)

2020-09-26 14:27 UTC, merged