DE #19 corrections
AlternativeFFFF/Alt-F4 pull request #361
Opened 2021-01-05 16:34 UTC by dexteritas

2021-01-06 09:04 UTC, Firerazer requested changes
Based on discord comment, the " is a formating thing, hence have to be handled by the language translators. Please adapt your text to it, and eventually review all others submissions

Rest is approved

2021-01-06 09:42 UTC, dexteritas commented
Since the quotation marks are otherwise also replaced by two separate characters (as is correct in English), it should be adjustable. At least I know that it works automatically on other websites, and you can set the language.

I have adjusted it for this now anyway again manually, in the previous editions it is already so.

2021-01-07 10:33 UTC, Firerazer approved these changes

2021-01-07 10:38 UTC, Conor12345 approved these changes

2021-01-07 10:38 UTC, merged